/**
 * Schema-derived test fixtures.
 *
 * Fixtures are generated by feeding the project's Zod schemas
 * (`src/lib/validations.ts` — the single source of truth for wire/DB/client
 * shapes) to `zod4-mock`, a deterministic schema-driven mock generator for
 * Zod v4. A fixed seed makes every run reproducible; thin per-test overrides
 * let a test pin the fields it cares about.
 *
 * The SAME fixtures feed both client (Dexie) and DB (pglite) tests, so there is
 * a single consistent data source: fixture → schema-validated object → insert.
 */
import { createWorld } from 'zod4-mock';
import {
	itemSchema,
	listSchema,
	type LocalItem,
	type LocalList
} from '$lib/validations';

/** Fixed seed → byte-identical fixtures on every run / machine. */
export const FIXTURE_SEED = 42;

/** A deterministic generator world, shared by all fixture builders. */
const world = createWorld({ seed: FIXTURE_SEED });

/** Build one `list` fixture, optionally overriding specific fields. */
export function listFixture(overrides: Partial<LocalList> = {}): LocalList {
	return { ...world.generate(listSchema), ...overrides };
}

/** Build one `item` fixture, optionally overriding specific fields. */
export function itemFixture(overrides: Partial<LocalItem> = {}): LocalItem {
	return { ...world.generate(itemSchema), ...overrides };
}
